### ISSUE TITLE
Why it is ok to use "Restricted" License?

### ISSUE THREAD

**Issue by ouwyukha** [whosonfirst/whosonfirst-sources#200]
Hello, I have limited knowledge on License.
I wonder why it is ok for [Who's On First](https://whosonfirst.org/) and derivated projects to use some of the sources when they have "Restricted" License?

For example, License from Factual:
```
"404734193": {
    "description": "Location data for Mobile Advertising, Developers, and Enterprise solutions.",
    "edtf:inception": "2015-09-08",
    "fullname": "Factual",
    "id": 404734193,
    "key": "id",
    "license": "http://factual.com/tos",
    "license_text": "All of the information and data made available via the Sites ('Site Data') is provided solely to enable you to learn about Factual and the Services. You are not licensed to store, copy, or use any Site Data for any other purpose.",
    "license_type": "Restricted",
    "name": "factual",
    "prefix": "fct",
    "url": "https://github.com/Factual/places",
    "usage_concordance": 1,
    "usage_geometry": 0,
    "usage_property": 0
  }
```

It says "_You are not licensed to store, copy, or use any Site Data for any other purpose._". But we can use it for concordance purposes?
I have also noticed [Location IQ](https://locationiq.com/attribution) used data from [Who's On First](https://whosonfirst.org/) for commercial purpose and it is also ok?

Please teach me as 5th grader, thank you.

**Comment by nvkelso** [comment]
Hey @ouwyukha, thank you for the great question! 

Sources in Who's On First with a **restricted** licenses are limited to only `"usage_concordance"`. This means that the Who's On First project can have an interoperability pointer from our place record to the restricted project's equivalent feature by storing the unique ID (for example: ID = "12345") of that place in the restricted data sources. We also store interoperability IDs for many open data sources, too. This makes the project easier to use because it's compatible with a wider range of systems. This type of usage is protected under United States of America law, based on past legal cases around "facts" and "interoperability". The Who's On First project is domiciled in the U.S. 

Restricted sources in Who's On First are however _prohibited_ from `"usage_geometry"` or `"usage_property"`. This mean Who's On First **can't** use the polygon or point geometries from the restricted source (the location of the feature), or anything about the feature (like it's names or population). 

When looked at with the [5 Ws](https://en.wikipedia.org/wiki/Five_Ws), a technique my 4th grader is just learning about:

- **Who:** This is the concordance. Everyone agrees that the person `Yukha` is a person, and there's enough context to know which `Yukha` because there are more than one person with that name. This is `"usage_concordance" = 1` where 1 means true or allowed.
- **What:** But what makes `Yukha` uniquely `Yukha`? This can be an endless list, some of which is commonly known by many other people, some by just your friends and family, and some just by you. We error on side of caution and say even if it's commonly known by many other people we won't import (in other words, `"usage_property": 0` where 0 means "false") into Who's On First from a restricted source.
- **When:** When was `Yukha` born and how old are you now? When is now? The population of a city is how much, but at what time? If everyone is pulling from the same publicly available government Census then those are facts (eg `"usage_property"`). If it was a common and open "fact", we'd instead go to the original open source to import them into Who's On First, not from the restricted source. It's worth noting that the names of a place change thru time! This is like you having a nickname as a kid, but when you grow up people will probably stop using the nickname and call you by your given birth name. 
- **Where:** Where was `Yukha` born? We can all agree some city name, in a country. But what specific latitude and longitude (eg `"usage_geometry"`) describes that location? I was born at home in a city: but should this be the centroid of the city, the city hall, or downtown? Or the building I was born in and it's centroid, or should it be the front door of the building, or the room in the house I was born? There are opinions wrapped up in which choice we make, and the pattern of choices that make up an entire database of places (and how consistent those choices are). Another way to think about this is if the latitude and longitude have X.xxx of precision then it's more commonly available and agreed on "facts" (though poorer accuracy), and X.xxxxxx you have high precision but an opinion about how one is describing the fact (which is restricted). Since there are opinions here, we also don't import point geometries. If those point geometries are like a stick figure drawing of you, then we especially don't want to import polygon geometries because those are more like a photo of you which is definitely restricted by copyright. Instead we'll look for an open data source to import instead, and sometimes we'll make our own geometries by using an open or cleared satellite imagery source, or by approximating it with distances and angles from other known places in our database. 
- **Why:** This is beyond the scope of Who's On First. Talk to your mom and dad ;)

This policy was reviewed for legal compliance by at least 2 lawyers for large publicly traded international companies, namely Samsung and Snapchat. Disclaimer I am not a lawyer and you asked for 5th grader explanation so you'd get a different explanation from an esquire. 

_NOTE: If you still feel uncomfortable using these concordances then you can drop them on import into your own database._
